name: Publish to NuGet

on:
  push:
    branches:
      - production

jobs:
  build_and_publish:
    runs-on: windows-2022
    environment: production  # Optional: only include if specified in your NuGet Trusted Publishing policy

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: nuget restore epay3.Sdk.V2.sln

    - name: Get version from .csproj
      id: get_version
      shell: pwsh
      run: |
        $match = Get-Content -Path 'src\epay3.Web.Api.Sdk.V2\epay3.Web.Api.Sdk.V2.csproj' | Select-String -Pattern '<Version>(.*)</Version>'
        if ($match -and $match.Matches.Count -gt 0) {
          $version = $match.Matches[0].Groups[1].Value
          echo "base_version=$version" >> $env:GITHUB_OUTPUT
        } else {
          Write-Error "Version tag not found in .csproj"
          exit 1
        }

    - name: Build solution
      run: msbuild epay3.Sdk.V2.sln /p:Configuration=Release

    - name: Pack NuGet package
      run: dotnet pack src\epay3.Web.Api.Sdk.V2\epay3.Web.Api.Sdk.V2.csproj --configuration Release --output ./nupkg --version ${{ steps.get_version.outputs.base_version }}.${{ github.run_number }}

    - name: Authenticate with NuGet
      uses: NuGet/login@v1
      id: nuget-login

    - name: Push to NuGet
      run: |
        nuget push ./nupkg/*.nupkg `
          -Source https://api.nuget.org/v3/index.json `
          -ApiKey ${{ steps.nuget-login.outputs.NUGET_API_KEY }} `
          -SkipDuplicate