name: Publish to NuGet

on:
  push:
    branches:
      - production

permissions:
  id-token: write
  contents: read

jobs:
  build_and_publish:
    runs-on: windows-2022
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: nuget restore epay3.Sdk.V2.sln

    - name: Get version from .csproj
      id: get_version
      shell: pwsh
      run: |
        $match = Get-Content -Path 'src\epay3.Web.Api.Sdk.V2\epay3.Web.Api.Sdk.V2.csproj' | Select-String -Pattern '<Version>(.*)</Version>'
        if ($match -and $match.Matches.Count -gt 0) {
          $version = $match.Matches[0].Groups[1].Value
          echo "base_version=$version" >> $env:GITHUB_OUTPUT
        } else {
          Write-Error "Version tag not found in .csproj"
          exit 1
        }

    - name: Build solution
      run: msbuild epay3.Sdk.V2.sln /p:Configuration=Release

    - name: Pack NuGet package
      run: dotnet pack src\epay3.Web.Api.Sdk.V2\epay3.Web.Api.Sdk.V2.csproj --configuration Release --output ./nupkg -p:Version=${{ steps.get_version.outputs.base_version }}.${{ github.run_number }}

    - name: Authenticate with NuGet
      uses: NuGet/login@v1
      id: nuget-login
      with:
        user: epay_arturo

    - name: Push to NuGet
      shell: pwsh
      run: |
        $packagePath = Get-ChildItem -Path ./nupkg -Recurse -Filter *.nupkg | Select-Object -ExpandProperty FullName
        
        if (-not $packagePath) {
          Write-Error "Failed to find the package file in ./nupkg"
          exit 1
        }

        dotnet nuget push $packagePath `
          --source https://api.nuget.org/v3/index.json `
          --api-key ${{ steps.nuget-login.outputs.NUGET_API_KEY }} `
          --skip-duplicate

    - name: Create Git tag
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag v${{ steps.get_version.outputs.base_version }}.${{ github.run_number }}
        git push origin v${{ steps.get_version.outputs.base_version }}.${{ github.run_number }}

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ steps.get_version.outputs.base_version }}.${{ github.run_number }}
        release_name: Release v${{ steps.get_version.outputs.base_version }}.${{ github.run_number }}
        body: |
          Published NuGet package version v${{ steps.get_version.outputs.base_version }}.${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}